version: "2"

services:

  fuseki:
    image: emetsger/apix-fuseki:2.3.1
    container_name: fuseki
    ports:
      - "3030:3030"

  fcrepo:
    image: emetsger/apix-fcrepo:4.6.0
    container_name: fcrepo
    ports:
      - "5006:5006"
      - "8080:8080"

  acrepo:
    image: emetsger/apix-acrepo:latest
    container_name: acrepo
    ports:
      - "5008:5008"
      - "9102:9102"
    depends_on:
      - fcrepo

  apix:
    image: emetsger/apix-core:latest
    container_name: apix
    env_file: apix.env
    ports:
      - "5009:5009"
      - "80:80"
      - "8081:8081"
    depends_on:
      - fcrepo
