version: "2"

services:

  fuseki:
    image: fcrepoapix/apix-fuseki:2.4.1
    container_name: fuseki
    ports:
      - "3030:8080"

  fcrepo:
    image: fcrepoapix/apix-fcrepo:4.7.1
    container_name: fcrepo
    env_file: apix.env
    ports:
      - "8080:80"
      - "5006:5006"

  indexing:
    image: fcrepoapix/apix-indexing:latest
    container_name: indexing
    env_file: apix.env
    ports:
      - "9090:9090"
      - "5010:5010"
    depends_on:
      - fcrepo
      - fuseki
    links:
      - apix:localhost

  acrepo:
    image: fcrepoapix/apix-acrepo:latest
    container_name: acrepo
    ports:
      - "9102:9102"
      - "9103:9103"
      - "9104:9104"
      - "9105:9105"
      - "9106:9106"
      - "9107:9107"
    depends_on:
      - fcrepo
    links:
      - apix:localhost

  apix:
    image: fcrepoapix/apix-core:latest
    container_name: apix
    env_file: apix.env
    ports:
      - "80:80"
      - "8081:8081"
    depends_on:
      - fcrepo

  fits:
    image: fcrepoapix/apix-fits:1.0.3
    container_name: fits
    ports:
      - "8082:8080"
